#!/usr/bin/bash

~/.config/lemonbar/bar.py DisplayPort-0 \
    | lemonbar \
        -a 20 \
        -f "Inconsolata:size=13" \
        -f "FontAwesome:size=12" \
        -F "#FFFFFFFF" \
        -B "#882F343F" \
        -g 2560x20 | zsh &

~/.config/lemonbar/bar.py HDMI-A-1 \
    | lemonbar \
        -a 20 \
        -f "Inconsolata:size=13" \
        -f "FontAwesome:size=12" \
        -F "#FFFFFFFF" \
        -B "#882F343F" \
        -g 1080+2560+1100 | zsh

wait
